export const TOGGLE_MENU = 'TOGGLE_MENU';
export const TOGGLE_FOUNDATIONS = 'TOGGLE_FOUNDATIONS';
export const TOGGLE_ORGANIZATIONS = 'TOGGLE_ORGANIZATIONS';
export const TOGGLE_LOCAL = 'TOGGLE_LOCAL';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';